// libs/ogl/platform/server/server.go
package oglserver

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"net/http"

	oglpfconfig "github.com/ovya/ogl/platform/config"
	oglmiddleware "github.com/ovya/ogl/platform/middleware"
	"github.com/rotisserie/eris"
)

// HTTPServer is a generic worker that manages the lifecycle of an HTTP server.
type HTTPServer struct {
	server  *http.Server
	logger  *slog.Logger
	appName string
	cfg     oglpfconfig.Server
}

// NewHTTPServer creates a pre-configured server ready to be started.
// TODO: add routes for monitoring
func NewHTTPServer(appName, environment string,
	cfg *oglpfconfig.Server, handler http.Handler, logger *slog.Logger) *HTTPServer {
	cfg.SetDefaults()

	addr := fmt.Sprintf("%s:%d", cfg.Host, cfg.Port)

	// We only log heavy JSON payloads in development to save production RAM
	logPayloads := environment == "development"

	loggerMiddleware := oglmiddleware.LoggingMiddleware(logger, logPayloads)
	recoveryMiddleware := oglmiddleware.RecoveryMiddleware(logger)
	corsMiddleware := oglmiddleware.CORSMiddleware(cfg, environment)

	// Chain Middlewares (Execution order goes outside-in)
	// Request -> Logger -> Recovery -> CORS -> Connect Handler
	// Logger (Outermost) -> Sees the 500 generated by the recovery
	// Recovery -> Catches panics from inner handlers
	// CORS -> Handles preflight headers
	// Handler (Innermost) -> the Connect RPC application
	finalHandler := loggerMiddleware(recoveryMiddleware(corsMiddleware(handler)))

	return &HTTPServer{
		server: &http.Server{
			Addr:              addr,
			Handler:           finalHandler,
			ReadHeaderTimeout: cfg.ReadHeaderTimeout,
			IdleTimeout:       cfg.IdleTimeout,
		},
		logger:  logger,
		appName: appName,
		cfg:     *cfg,
	}
}

// Start blocks until the context is canceled, then performs a graceful shutdown.
func (s *HTTPServer) Start(ctx context.Context) error {
	errChan := make(chan error, 1)

	// 1. Start the server in the background
	go func() {
		s.logger.Info("starting http server", "name", s.appName, "addr", s.server.Addr)
		if err := s.server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			errChan <- eris.Wrapf(err, "server %s crashed", s.appName)
		}
		close(errChan)
	}()

	// 2. Wait for either a fatal crash OR a shutdown signal from the Runner
	select {
	case err := <-errChan:
		// The server crashed on startup (e.g., port already in use)
		return err

	case <-ctx.Done():
		// The global context was canceled (Ctrl+C). Time to shut down cleanly.
		s.logger.Info("initiating graceful shutdown", "name", s.appName)

		shutdownCtx, cancel := context.WithTimeout(context.Background(), s.cfg.ShutdownTimeout)
		defer cancel()

		if err := s.server.Shutdown(shutdownCtx); err != nil {
			return eris.Wrapf(err, "failed to shutdown server %s cleanly", s.appName)
		}

		s.logger.Info("server stopped gracefully", "name", s.appName)

		return nil
	}
}
