// libs/ogl/platform/server/server.go
package oglserver

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/pprof"
	"runtime/debug"

	oglpfconfig "github.com/ovya/ogl/platform/config"
	oglmiddleware "github.com/ovya/ogl/platform/middleware"
	"github.com/rotisserie/eris"
)

// HTTPServer is a generic worker that manages the lifecycle of an HTTP server.
type HTTPServer struct {
	server *http.Server
	logger *slog.Logger
	cfg    oglpfconfig.Server
}

type HealthFns = map[string]func(context.Context) (any, error)

type HTTPServerInfra struct {
	Config      *oglpfconfig.Server
	Handler     http.Handler
	Logger      *slog.Logger
	HealthFns   HealthFns
	LogPayloads bool
}

// NewHTTPServer creates a pre-configured server ready to be started.
func NewHTTPServer2(withDebugRoutes bool, infra HTTPServerInfra) *HTTPServer {
	infra.Config.SetDefaults()

	addr := fmt.Sprintf("%s:%d", infra.Config.Host, infra.Config.Port)

	// Mount monitoring routes alongside the application handler.
	mux := http.NewServeMux()

	// Health and readiness probes (always available).
	mux.HandleFunc("GET /debug/monit", func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		msgs, hasErr := getMonitMessages(infra.HealthFns)

		// Must be write before writing the response
		if hasErr {
			w.WriteHeader(http.StatusInternalServerError)
		} else {
			w.WriteHeader(http.StatusOK)
		}

		_ = json.NewEncoder(w).Encode(msgs)
	})

	if withDebugRoutes {
		mux.HandleFunc("GET /debug/info", func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", "application/json; charset=utf-8")
			w.WriteHeader(http.StatusOK)
			// json.NewEncoder(w).Encode(map[string]string{"message": "success"})
			writeProcessInfo(w)
		})
		mux.HandleFunc("/debug/pprof/", pprof.Index)
		mux.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
		mux.HandleFunc("/debug/pprof/profile", pprof.Profile)
		mux.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
		mux.HandleFunc("/debug/pprof/trace", pprof.Trace)
	}

	// All other requests go to the application handler.
	mux.Handle("/", infra.Handler)

	loggerMiddleware := oglmiddleware.LoggingMiddleware(infra.Logger, infra.LogPayloads)
	recoveryMiddleware := oglmiddleware.RecoveryMiddleware(infra.Logger)
	corsMiddleware := oglmiddleware.CORSMiddleware(infra.Config)

	// Chain Middlewares (Execution order goes outside-in)
	// Request -> Logger -> Recovery -> CORS -> Mux
	// Logger (Outermost) -> Sees the 500 generated by the recovery
	// Recovery -> Catches panics from inner handlers
	// CORS -> Handles preflight headers
	// Mux (Innermost) -> monitoring routes + Connect RPC application
	finalHandler := loggerMiddleware(recoveryMiddleware(corsMiddleware(mux)))

	return &HTTPServer{
		server: &http.Server{
			Addr:              addr,
			Handler:           finalHandler,
			ReadHeaderTimeout: infra.Config.ReadHeaderTimeout,
			IdleTimeout:       infra.Config.IdleTimeout,
		},
		logger: infra.Logger,
		cfg:    *infra.Config,
	}
}

func getMonitMessages(fns HealthFns) (msgs map[string]any, hasErr bool) {
	msgs = map[string]any{}
	ctx := context.Background()
	var err error
	for key, fn := range fns {
		msgs[key], err = fn(ctx)
		if err != nil {
			msgs[key] = fmt.Sprintf("%s", err)
			hasErr = true
		}
	}

	hm := 42
	if hasErr {
		hm = 0
	}
	msgs["happiness-message"] = hm

	return
}

func writeProcessInfo(w io.Writer) {
	if bi, ok := debug.ReadBuildInfo(); ok {
		encoder := json.NewEncoder(w)
		encoder.SetIndent("", "  ") // Pretty-print
		_ = encoder.Encode(bi)
		// fmt.Printf("Version: %s\n", bi.Main.Version)
		// fmt.Printf("Go Version: %s\n", bi.GoVersion)
		// fmt.Printf("Git Revision: %s\n", bi.Settings["vcs.revision"])
		// fmt.Printf("Build Time: %s\n", bi.Settings["vcs.time"])
		// fmt.Fprintf(w, `{"pid": "%d"}`, os.Getpid())
	}
}

// Start blocks until the context is canceled, then performs a graceful shutdown.
func (s *HTTPServer) Start(ctx context.Context) error {
	errChan := make(chan error, 1)

	// 1. Start the server in the background
	go func() {
		s.logger.Info("starting http server", "addr", s.server.Addr)
		if err := s.server.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			s.logger.Error("server crashed")
			errChan <- eris.Wrap(err, "server crashed")
		}
		close(errChan)
	}()

	// 2. Wait for either a fatal crash OR a shutdown signal from the Runner
	select {
	case err := <-errChan:
		// The server crashed on startup (e.g., port already in use)
		return err

	case <-ctx.Done():
		// The global context was canceled (Ctrl+C). Time to shut down cleanly.
		s.logger.Info("initiating graceful shutdown")

		shutdownCtx, cancel := context.WithTimeout(context.Background(), s.cfg.ShutdownTimeout)
		defer cancel()

		if err := s.server.Shutdown(shutdownCtx); err != nil {
			msg := "failed to shutdown server %s cleanly"
			s.logger.Error(msg)

			return eris.Wrap(err, msg)
		}

		s.logger.Info("server stopped gracefully")

		return nil
	}
}
