package checks_test

import (
	"os"
	"testing"

	"github.com/piprim/mmw/internal/pkg/checks"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestFormatChecker_Name(t *testing.T) {
	assert.Equal(t, "format", checks.NewFormatChecker().Name())
}

func TestFormatChecker_Check(t *testing.T) {
	t.Run("already formatted file has no violations", func(t *testing.T) {
		src := "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfmt.Println(\"hello\")\n}\n"
		path := writeTemp(t, "clean.go", src)
		result, err := checks.NewFormatChecker().Check(t.Context(), []string{path})
		require.NoError(t, err)
		assert.False(t, result.HasViolations(), "already-formatted file should have no violations")
	})

	t.Run("unformatted file reports violation with file path", func(t *testing.T) {
		unformatted := "package main\n\n\nimport \"fmt\"\n\n\nfunc main() {\nfmt.Println(\"hello\")\n}\n"
		path := writeTemp(t, "dirty.go", unformatted)
		result, err := checks.NewFormatChecker().Check(t.Context(), []string{path})
		require.NoError(t, err)
		assert.True(t, result.HasViolations(), "unformatted file should report a violation")
		assert.Equal(t, path, result.Violations[0].File)
	})

	t.Run("skips non-Go files", func(t *testing.T) {
		path := writeTemp(t, "config.yaml", "key: val\n")
		result, err := checks.NewFormatChecker().Check(t.Context(), []string{path})
		require.NoError(t, err)
		assert.False(t, result.HasViolations(), "non-Go files must be skipped")
	})
}

func TestFormatChecker_Fix(t *testing.T) {
	t.Run("formats unformatted file in-place so re-check passes", func(t *testing.T) {
		unformatted := "package main\n\n\nimport \"fmt\"\n\n\nfunc main() {\nfmt.Println(\"hello\")\n}\n"
		path := writeTemp(t, "fix.go", unformatted)

		fixer, ok := checks.NewFormatChecker().(checks.Fixer)
		require.True(t, ok, "formatChecker must implement Fixer")
		require.NoError(t, fixer.Fix(t.Context(), []string{path}))

		result, err := checks.NewFormatChecker().Check(t.Context(), []string{path})
		require.NoError(t, err)
		assert.False(t, result.HasViolations())
	})
}

// generatedBody mirrors what protoc-gen-go emits for a file with an enum:
// a single-declaration var group and a redundant conversion paren, both of
// which gofumpt rewrites. See contracts/go/network/*/v1/*.pb.go.
const generatedBody = "package p\n\ntype E int32\n\nvar (\n\tgoTypes = []any{\n\t\t(E)(0),\n\t}\n)\nvar depIdxs = []int32{}\n"

const generatedHeader = "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n"

func TestFormatChecker_GeneratedFiles(t *testing.T) {
	t.Run("fixture is unformatted without the generated header", func(t *testing.T) {
		path := writeTemp(t, "handwritten.go", generatedBody)

		result, err := checks.NewFormatChecker().Check(t.Context(), []string{path})
		require.NoError(t, err)
		assert.True(t, result.HasViolations(), "the fixture must be gofumpt-dirty for this suite to mean anything")
	})

	t.Run("generated file reports no violation", func(t *testing.T) {
		path := writeTemp(t, "gen.pb.go", generatedHeader+generatedBody)

		result, err := checks.NewFormatChecker().Check(t.Context(), []string{path})
		require.NoError(t, err)
		assert.False(t, result.HasViolations(), "generated files must be skipped")
	})

	t.Run("Fix leaves a generated file byte-identical", func(t *testing.T) {
		src := generatedHeader + generatedBody
		path := writeTemp(t, "gen.pb.go", src)

		fixer, ok := checks.NewFormatChecker().(checks.Fixer)
		require.True(t, ok, "formatChecker must implement Fixer")
		require.NoError(t, fixer.Fix(t.Context(), []string{path}))

		after, err := os.ReadFile(path)
		require.NoError(t, err)
		assert.Equal(t, src, string(after), "--fix must not rewrite generated files; codegen would undo it")
	})
}
