package checks_test

import (
	"path/filepath"
	"testing"

	"github.com/piprim/mmw/internal/pkg/checks"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIsGenerated(t *testing.T) {
	t.Run("canonical protoc header is generated", func(t *testing.T) {
		src := "// Code generated by protoc-gen-go. DO NOT EDIT.\n" +
			"// versions:\n" +
			"// \tprotoc-gen-go v1.36.12\n" +
			"// source: auth/v1/auth.proto\n\n" +
			"package authv1\n"
		path := writeTemp(t, "auth.pb.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.True(t, generated)
	})

	t.Run("marker after a build constraint is generated", func(t *testing.T) {
		src := "//go:build !race\n\n" +
			"// Code generated by stringer. DO NOT EDIT.\n\n" +
			"package p\n"
		path := writeTemp(t, "build.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.True(t, generated)
	})

	t.Run("marker after the package clause is not generated", func(t *testing.T) {
		src := "package p\n\n" +
			"// Code generated by protoc-gen-go. DO NOT EDIT.\n" +
			"var x = 1\n"
		path := writeTemp(t, "late.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.False(t, generated, "the marker only counts before the package clause")
	})

	t.Run("marker inside a string literal is not generated", func(t *testing.T) {
		src := "package p\n\n" +
			"func header() string {\n" +
			"\treturn \"// Code generated by protoc-gen-go. DO NOT EDIT.\"\n" +
			"}\n"
		path := writeTemp(t, "literal.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.False(t, generated)
	})

	t.Run("marker without the DO NOT EDIT suffix is not generated", func(t *testing.T) {
		src := "// Code generated by hand, mostly.\n\npackage p\n"
		path := writeTemp(t, "partial.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.False(t, generated, "the full Go convention suffix is required")
	})

	t.Run("hand-written file is not generated", func(t *testing.T) {
		src := "// Package p does things.\npackage p\n"
		path := writeTemp(t, "plain.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.False(t, generated)
	})

	t.Run("CRLF line endings are handled", func(t *testing.T) {
		src := "// Code generated by protoc-gen-go. DO NOT EDIT.\r\n\r\npackage p\r\n"
		path := writeTemp(t, "crlf.go", src)

		generated, err := checks.IsGenerated(path)
		require.NoError(t, err)
		assert.True(t, generated)
	})

	t.Run("missing file returns an error", func(t *testing.T) {
		_, err := checks.IsGenerated(filepath.Join(t.TempDir(), "absent.go"))
		require.Error(t, err)
	})
}
